/**
  ******************************************************************************
  * @file    app.c
  * @brief   Glue between CubeMX-generated init and the Euclid application.
  ******************************************************************************
  */

#include "app.h"
#include "seq_engine.h"
#include "ui.h"
#include "euclid_config.h"

#if EUCLID_DEBUG_UART
#include <stdio.h>
#endif

/* Generated by CubeMX in tim.c. If you enabled "generate a pair of .c/.h files
   per peripheral" these are already declared in tim.h; the externs are harmless
   either way and keep this module independent of that setting. */
extern TIM_HandleTypeDef htim1;     /* master step clock + 4 gate PWM channels */
extern TIM_HandleTypeDef htim2;     /* encoder: Tempo   PA0 / PA1  */
extern TIM_HandleTypeDef htim3;     /* encoder: N       PA6 / PA4  */
extern TIM_HandleTypeDef htim4;     /* encoder: K1      PA11 / PA12 */
extern TIM_HandleTypeDef htim5;     /* encoder: K2      PB2 / PC12 */
extern TIM_HandleTypeDef htim8;     /* encoder: K3      PC6 / PC7  */
extern TIM_HandleTypeDef htim17;    /* one-shot: ends SOC + clock pulses */

void app_init(void)
{
    ui_init(&htim2, &htim3, &htim4, &htim5, &htim8);
    seq_init(&htim1, &htim17);

#if EUCLID_DEBUG_UART
    printf("\r\nEuclid 1  --  %lu Hz tick, %u steps/beat\r\n",
           (unsigned long)SEQ_TIMER_HZ, (unsigned)SEQ_STEPS_PER_BEAT);
    printf("tempo %u BPM  N %u  gate %u%%  k = %u/%u/%u\r\n",
           seq.tempo_bpm, seq.n, seq.gate_pct, seq.k[0], seq.k[1], seq.k[2]);
#endif
}

void app_tick(void)
{
    ui_tick();          /* rate-limits itself to UI_POLL_INTERVAL_MS */
    seq_service();      /* regenerates patterns only when something changed */
}

/* -------------------------------------------------------------------------- */
/* HAL interrupt dispatch                                                     */
/* -------------------------------------------------------------------------- */

/**
  * @brief  Single HAL callback for every timer update event. Keep both branches
  *         short -- TIM1 runs at priority 0 and is the musical timing source.
  *
  *         Never call HAL_Delay() or anything that polls HAL_GetTick() from
  *         here: SysTick sits at a lower priority and cannot preempt these, so
  *         it would hang rather than time out.
  */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
    if (htim->Instance == TIM1)
    {
        seq_on_step();
    }
    else if (htim->Instance == TIM17)
    {
        seq_on_trigger_end();
    }
}

#if EUCLID_DEBUG_UART
/* Route printf to USART2, which is wired to the ST-Link virtual COM port. */
extern UART_HandleTypeDef huart2;

int __io_putchar(int ch)
{
    HAL_UART_Transmit(&huart2, (uint8_t *)&ch, 1, HAL_MAX_DELAY);
    return ch;
}
#endif
