/**
  ******************************************************************************
  * @file    app.c
  * @brief   Glue between CubeMX-generated init and the Euclid application.
  ******************************************************************************
  */

#include "app.h"
#include "seq_engine.h"
#include "ui.h"
#include "display.h"
#include "euclid_config.h"

#if EUCLID_DEBUG_UART
#include <stdio.h>
#endif

/* Generated by CubeMX in main.c. */
extern TIM_HandleTypeDef htim1;     /* master step clock + 4 gate PWM channels */
extern TIM_HandleTypeDef htim2;     /* encoder: Tempo   PA0 / PA1   */
extern TIM_HandleTypeDef htim3;     /* encoder: N       PA6 / PA4   */
extern TIM_HandleTypeDef htim4;     /* encoder: K1      PA11 / PA12 */
extern TIM_HandleTypeDef htim5;     /* encoder: K2      PB2 / PC12  */
extern TIM_HandleTypeDef htim8;     /* encoder: K3      PC6 / PC7   */
extern TIM_HandleTypeDef htim17;    /* one-shot: ends SOC + clock pulses */

void app_init(void)
{
    ui_init(&htim2, &htim3, &htim4, &htim5, &htim8);
    seq_init(&htim1, &htim17);
    display_init();

#if EUCLID_DEBUG_UART
    /* stdout is buffered by default, so short printf output can sit in the
       buffer and never appear -- you conclude the code didn't run when it did.
       Unbuffered means every character goes straight out. */
    setvbuf(stdout, NULL, _IONBF, 0);

    printf("\r\nEuclid 1  --  %lu Hz tick, %u steps/beat\r\n",
           (unsigned long)SEQ_TIMER_HZ, (unsigned)SEQ_STEPS_PER_BEAT);
    printf("tempo %u BPM  N %u  gate %u%%  k = %u/%u/%u\r\n",
           seq.tempo_bpm, seq.n, seq.gate_pct, seq.k[0], seq.k[1], seq.k[2]);
    printf("ARR %u  gate_ticks %u  running %u\r\n",
           seq.arr, seq.gate_ticks, seq.running);
#endif
}

void app_tick(void)
{
    ui_tick();          /* rate-limits itself to UI_POLL_INTERVAL_MS */
    seq_service();      /* regenerates patterns only when something changed */
    display_tick();     /* redraws only when something visible changed */
}

/* -------------------------------------------------------------------------- */
/* HAL interrupt dispatch                                                     */
/* -------------------------------------------------------------------------- */

/**
  * @brief  Single HAL callback for every timer update event. Keep both branches
  *         short -- TIM1 runs at priority 0 and is the musical timing source.
  *
  *         Never call HAL_Delay() or anything that polls HAL_GetTick() from
  *         here: SysTick sits at a lower priority and cannot preempt these, so
  *         it would hang rather than time out.
  */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
    if (htim->Instance == TIM1)
    {
        seq_on_step();
    }
    else if (htim->Instance == TIM17)
    {
        seq_on_trigger_end();
    }
}

/* -------------------------------------------------------------------------- */
/* printf retargeting -- deliberately NOT done here                            */
/* -------------------------------------------------------------------------- */
/*
 * The Nucleo BSP already provides __io_putchar(). stm32g4xx_nucleo_conf.h sets
 * both USE_BSP_COM_FEATURE and USE_COM_LOG to 1, which compiles a version in
 * stm32g4xx_nucleo.c that transmits to hcom_uart[COM_ActiveLogPort] -- and
 * COM_ActiveLogPort defaults to COM1, the LPUART1 wired to the ST-Link VCP.
 *
 * So printf() already reaches the console with no work from us. Defining our
 * own __io_putchar() here collided with the BSP's at link time:
 *
 *     multiple definition of `__io_putchar'
 *
 * If you ever want to own it yourself, set USE_COM_LOG to 0 in
 * stm32g4xx_nucleo_conf.h first -- that removes the BSP's definition.
 *
 * BSP_COM_Init() runs AFTER the USER CODE 2 block in main.c, which is why
 * app_init() is called from USER CODE BEGIN WHILE instead. Printing before the
 * BSP has configured the UART sends bytes nowhere.
 */
